% Parameters

projectName = 'combine';
saveLocation = 'C:\Users\bv8\Desktop\analysis\combine\';

acclimationTiming = 	[0	4800];
baselineTiming =	[4800	5400];
eventTiming = 	[0	1	29];


groupingFile = {'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\161012_0B\161012_0Bgenotype.txt',...
                'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\161212_0A\161212_0Agenotype.txt',...
                'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\170118_0A\170118_0Agenotype.txt'};
            
viewPointFile = {'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\161012_0B\161012_0B.xlsx',...
    'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\161212_0A\161212_0A.xlsx',...
    'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\170118_0A\170118_0A.xlsx'};


timingFile = 'C:\Users\bv8\Desktop\analysis\combine\Chd8 del5 Lights off\161012_0B\161012_0BTiming.txt';

dv = 'actinteg';
groupName = 'grp_GroupLabel_1';
eventIndex = 'Light';
eventLabel = 'off';
number_of_events = 5;



postEventLabel = sprintf('post_%s',eventLabel); 
contrast = {eventLabel postEventLabel};
repContrast = {sprintf('%s_1',eventLabel) sprintf('%s_%d',eventLabel,number_of_events')};



% Creating the data object

 n = animalBehaviorAnalysis('PROJECT_NAME',projectName,...
    'SAVE_LOCATION',saveLocation,...
    'ACCLIMATION_TIMING', acclimationTiming,...
    'EVENT_TIMING',eventTiming,...
    'BASELINE_TIMING',baselineTiming,...
    'GROUPING_FILE', groupingFile,...
    'VIEWPOINT_FILE',viewPointFile,...
    'TIMING_FILE',timingFile);


%%
A = n.timeSeriesPlot('DV',dv,...
                     'GROUPBY',groupName,...
                     'NORMBYBASELINE',1,...
                      'TITLE','Time series plot 1');
                 
%
% A = n.timeSeriesPlot('DV',dv,...
%                      'GROUPBY',groupName,...
%                      'EVENTINDEX',eventIndex,...
%                    'EVENTLABEL',eventLabel,...
%                      'SUPRESSBASELINE',1,...
%                      'SUPRESSACCLIMATION',1,...
%                      'NORMBYBASELINE',1);
%                  
%  %
%  A = n.timeSeriesPlot('DV',dv,...
%                      'GROUPBY',groupName,...
%                      'EVENTINDEX',eventIndex,...
%                    'EVENTLABEL',eventLabel,...
%                      'SUPRESSBASELINE',1,...
%                      'SUPRESSACCLIMATION',1,...
%                      'NORMBYBASELINE',0);
  A = n.timeSeriesPlot('DV',dv,...
                     'GROUPBY',groupName,...
                     'EVENTINDEX',eventIndex,...
                   'EVENTLABEL',eventLabel,...
                     'SUPRESSBASELINE',1,...M
                     'SUPRESSACCLIMATION',1,...
                     'NORMBYBASELINE',1,...
                      'TITLE','Time series plot 2');

% Groupwise test of common baseline
n.stats('ANALYSISNAME','baseline',...
    'DV',{dv},...
    'EVENTINDEX',{'common_baseline'},...
    'EVENTLABEL',{1},...
    'EVENTPERIODLABEL',{'common_baseline'},...
    'GROUPBY',{groupName},...
    'SPLITEVENTS',0,...
    'STATPLOTS',0,...
    'SUPRESSPLOT',1,...
    'SUPRESSEXCEL',1);
%%
% Test of Event normed to baseline, by Groups
n.stats('ANALYSISNAME','eventXgroup',...
    'DV',{dv},...
    'GROUPBY',{groupName},...
    'EVENTINDEX',{eventIndex},...
    'EVENTLABEL',{eventLabel},...
    'CONTRAST',[],...
    'EVENTPERIODLABEL',{'event'},...
    'EVENTNORMBYBASELINE',1,...
    'SPLITEVENTS',0,...
    'STATPLOTS',0,...
    'SUPRESSPLOT',1,...
    'SUPRESSEXCEL',1);
%  Test of Post Event normed to baseline, by Groups
n.stats('ANALYSISNAME','posteventXgroup',...
    'DV',{dv},...
    'GROUPBY',{groupName},...
    'EVENTINDEX',{eventIndex},...
    'EVENTLABEL',{eventLabel},...
    'CONTRAST',{postEventLabel},...
    'EVENTPERIODLABEL',{'event'},...
    'EVENTNORMBYBASELINE',1,...
    'SPLITEVENTS',0,...
    'STATPLOTS',0,...
    'SUPRESSPLOT',1,...
    'SUPRESSEXCEL',1);
%  Test of contrast between event/post event by groups

n.stats('ANALYSISNAME','eventVSpost',...
    'DV',{dv},...
    'GROUPBY',{groupName},...
    'EVENTINDEX',{eventIndex},...
    'EVENTLABEL',{eventLabel},...
    'EVENTPERIODLABEL',{'event'},...
    'EVENTNORMBYBASELINE',1,...
    'SPLITEVENTS',0,...
    'CONTRAST',contrast,...
    'STATPLOTS',0,...
    'SUPRESSPLOT',1,...
    'SUPRESSEXCEL',1);

% Test of contrast between event/post event by groups

n.stats('ANALYSISNAME','et1VSet5',...
    'DV',{dv},...
    'GROUPBY',{groupName},...
    'EVENTINDEX',{eventIndex},...
    'REPETITION',1,...
    'EVENTLABEL',{eventLabel},...
    'EVENTPERIODLABEL',{'event'},...
    'SPLITEVENTS',1,...
    'EVENTNORMBYBASELINE',1,...
    'CONTRAST',repContrast,...
    'STATPLOTS',0,...
    'SUPRESSPLOT',1,...
    'SUPRESSEXCEL',1);




